### ISSUE TITLE
Workbook - Chapter 7

### ISSUE THREAD

**Issue by IzabelaM** [siwells/teaching_set09103#10]
I am not sure whether the 'bootstrap-3.3.5-dist.zip' is a correct folder name (workbook.tex, line 1968) - in my case the name of the downloaded folder is 'bootstrap.zip'. 
![bootstrap](https://user-images.githubusercontent.com/9845448/31586598-08481b88-b1cb-11e7-9b18-6e8a393f68c6.PNG)

**Comment by siwells** [comment]
You're entirely correct. I've fixed this & pushed the changes.
