### ISSUE TITLE
Misalignment in workbook [Chapter 7.1]

### ISSUE THREAD

**Issue by shortymike123** [siwells/teaching_set09103#3]
In the HTML code on page 67, line 4 reads `< link href ="{{ url_for ( ’ static ’, filename = ’css / bootstrap .min .css
’) }}" rel ="st`

Where it should read `<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" />` as shown on the code on github.

**Comment by Ivan-Roger** [comment]
The workbook on moodle hasn't been updated and still contains this misalignment.
