### ISSUE TITLE
Workbook - Chapter 1 - missing footnotes

### ISSUE THREAD

**Issue by IzabelaM** [siwells/teaching_set09103#6]
Following footnotes are missing (Chapter 1, Learning environment - Part 1):
* 15 - Git SCM book (page 16)
* 16 - create Github account (page 17)
* 17 - create Bitbucket account (page 17)

I believe the following links should be correct:
* 15 - https://git-scm.com/book/en/v2
* 16 - https://github.com/join
* 17 - https://bitbucket.org/account/signup/

**Comment by siwells** [comment]
Fixed. For some reason the frame tag interferes with footnotes. Might be a core LaTeX issue, or an issue with the way I was doing framing. Either way, easiest solution was to not frame that bit of text
